<a href="https://colab.research.google.com/github/Wajid0005/CAMPUS-X-notebooks/blob/main/Copy_of_task_22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import re

pd.options.display.max_columns = None

### `Question-1:`

The dataset is based on NFTs. This is quite large. So, when you will read the dataset, you have to wait. The link of the dataset: https://tinyurl.com/2pfhncqw

Your task is to make a pivote table by using the columns "verification_status", "contract_type", "rarity_score" and "last_sale_price" to find out the total values.

In [3]:
df = pd.read_csv("https://tinyurl.com/2pfhncqw")
df.head()

HTTPError: HTTP Error 410: Gone

### `Question-2:`

You are given a dataset about the cars' price and miles driven of different cars throughout the different years. The link of the dataset: https://tinyurl.com/2r24n45l. Your tasks are
- make a pivot table of the brands (the required brands are given below) from the "Year" 2018 to the year 2022 in which the "Price" is shown as average values and "Miles" are in median values. In this pivote table, every row represents a particular brand and each column represents either average "Price" of a partucular year or median values of "Miles" of a particular year.
- At the end plot a kde chart for the "Price" and "Miles" by using your pivot table.

There are some challenges to solve this task:
- There is no column that is represented to the brand name of the car. You have to find out on your own.
- Some values of "Years" column are misleading. You have to reset this column too that every value should tell a valid meaning.

In [ ]:
df = pd.read_csv("https://tinyurl.com/2r24n45l")
df['Name'].str.split().str[0]

In [ ]:
df['brand'] = df['Name'].str.split().str[0]
df.head(10)

In [ ]:
df['Year'] = df['Year'].astype(str).str[:4].astype(int)

In [ ]:
df.Year.unique()

In [ ]:
df_filtered = df[(df['Year'] >= 2018)& (df['Year'] <= 2022)]
df_filtered

In [ ]:
pivot_price = df_filtered.pivot_table(values='Price', index='brand', columns='Year', aggfunc='mean')
pivot_miles = df_filtered.pivot_table(values='Miles', index='brand', columns='Year', aggfunc='median')

pivot_price.columns = [f'AvgPrice_{y}' for y in pivot_price.columns]
pivot_miles.columns = [f'MedMiles_{y}' for y in pivot_miles.columns]

pivot = pd.concat([pivot_price, pivot_miles], axis=1)
pivot.stack().swaplevel().unstack()

### `Question-3:`

You are given a dataset of **Daily Power Generation in India** of regional wise of all Power Stations. Link of the dataset: https://tinyurl.com/2nq6kugt

Task
- In this dataset, there are many columns. Two of them are `Actual(MU)` and `Excess(+) / Shortfall (-)`. `Actual(MU)` represents the actual power generation. `Excess(+) / Shortfall (-)` tells is that generated power is excess or shortfall for that particular day of a power station. You have to find out what should be the actual power generation required for that day by the power stations that there would not be any excess or shorfall power. For the result, make a new column.
- Find out the month of the day and store it as a new column.
- Find out top 10 frequently appeared power stations in this dataframe.
- Next create a pivot table of which every row represents a power station and every column represents a month in a order. Like January, February, March...
- It is hard to get inside if you look through the only pivot table. So plot the pivot table.

In [ ]:
df = pd.read_csv("https://tinyurl.com/2nq6kugt")

In [ ]:
df.sample(5)

###`Q-4` You are given a file `question-answer.csv`. Your task is to make a dataframe from it with two columns - `question` and `answers`.

* Questions in the file start from `Q<number>`; E.g.  `Q1` denotes question no. `1`
* Answers starts from `Ans<number>`; Eg. `Ans1` denotes answer of question no `1`
* MAke sure you look at columns name carefully

CSV File - "https://drive.google.com/file/d/10rmV3XrVtzpDTtYZF3UtCdcU0ajBJjGY/view?usp=share_link"

In [ ]:
df = pd.read_csv("https://drive.google.com/uc?id=10rmV3XrVtzpDTtYZF3UtCdcU0ajBJjGY&export=download")

In [ ]:
df.sample()

In [ ]:
df['2'][0]

In [ ]:
df.drop(columns='Unnamed: 0', inplace = True)

In [ ]:
questions_list = []
answers_list = []

# Iterate through the DataFrame's '2' column with index
for i in range(len(df['2'])):
    if i % 2 == 0:  # Even index for questions
        questions_list.append(df['2'][i])
    else:  # Odd index for answers
        answers_list.append(df['2'][i])

# Create a new DataFrame from the lists
df_qa = pd.DataFrame({
    'question': questions_list,
    'answer': answers_list
})

# Clean up the 'question' and 'answer' columns by removing the prefixes
df_qa['question'] = df_qa['question'].str.replace(r'^Q\d+\-\s*', '', regex=True)
df_qa['answer'] = df_qa['answer'].str.replace(r'^Ans\d+\-\s*', '', regex=True)

display(df_qa)

df_qa['question'][1]

In [ ]:
df_qa['question'][1] = 'How is logistic regression done?'

In [ ]:
df_qa

*italicized text*###`Q-5`: Print Question and answer of those questions which does not contains any question mark (`?`).

In [ ]:
filtered_df = df_qa[~df_qa['question'].str.contains('\?')]

In [ ]:
filtered_df

###`Q 6-10` LOG and EMPLOYEE
6. Show `activity` details month wise. Show count for each `activity`
7. Find employee who did most `activity` in January month.
8. Employee who have worked most no of times on Weekends.
9. Which activity is logged most on buisness days.
10. Week Days wise activity table.
```
log_file = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT-OMrmmNdOTM-B5f5F1EpCutMVG230UZiLvqlsg0NIKUKR3yrqiI2r1pEX-LvSEk-3WwySPYtvbBC-/pub?gid=1937029224&single=true&output=csv")
employee = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQ5AuFqRjSZVBKm5zyDxquX6utubq1DJKkYDI70vjeidAnyAu70KMSYpMYzeVSNVTeUIJBpfF6jU5E6/pub?gid=798824749&single=true&output=csv")

```

Note(for common field):- Employee file has `EMPLOYEE_ID` and LOG file has `emp_id`

In [4]:
log_file = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT-OMrmmNdOTM-B5f5F1EpCutMVG230UZiLvqlsg0NIKUKR3yrqiI2r1pEX-LvSEk-3WwySPYtvbBC-/pub?gid=1937029224&single=true&output=csv")
employee = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQ5AuFqRjSZVBKm5zyDxquX6utubq1DJKkYDI70vjeidAnyAu70KMSYpMYzeVSNVTeUIJBpfF6jU5E6/pub?gid=798824749&single=true&output=csv")

In [5]:
log_file.sample(5)

     Log_ID          dt   dept  emp_id    activity     eqpt
329    1329  2022-12-02  Dept2     140    Cleaning      CPU
354    1354  2022-12-27  Dept3     134  Inspection      Fan
356    1356  2022-12-29  Dept1     149    Cleaning      UPS
204    1204  2022-07-30  Dept2     135  Inspection      UPS
151    1151  2022-06-07  Dept4     133    Checking  Battery

In [6]:
employee.sample(5)

    EMPLOYEE_ID FIRST_NAME LAST_NAME     EMAIL
13          113       Luis      Popp     LPOPP
25          125      Julia     Nayer    JNAYER
39          139       John       Seo      JSEO
1           101      Neena   Kochhar  NKOCHHAR
38          138    Stephen    Stiles   SSTILES

In [9]:
log_file.rename(columns= {'dt':'date'}, inplace= True)

In [12]:
log_file['date'] = pd.to_datetime(log_file['date'])

In [14]:
data = pd.merge(log_file, employee, left_on='emp_id', right_on='EMPLOYEE_ID')

In [18]:
data = data[['Log_ID','emp_id','date','FIRST_NAME', 'LAST_NAME', 'dept','activity','eqpt','EMAIL']]

In [23]:
#6
print('Month wise activity')
data.groupby(data['date'].dt.month)['activity'].value_counts().swaplevel().unstack()

Month wise activity

date        1   2   3   4   5   6   7   8   9   10  11  12
activity
Checking     6   4   6   3   4   4   5   7   8  11   6   5
Cleaning     9   6   4   9   7   5   5   9   2   3   9   4
Inspection   7   4   4   7   6   8  10   9  10   5   4   7
Repair       5  10  12   2   8   9   2   4   5   5   6   5

In [35]:
data[data['date'].dt.month == 1] \ .groupby(data['emp_id'])['activity'].value_counts().sort_index(ascending = False).head()

emp_id  activity
140     Repair        2
        Inspection    1
        Cleaning      2
        Checking      3
139     Repair        4
Name: count, dtype: int64

In [47]:
data['full_name'] = data['FIRST_NAME'] + ' ' + data['LAST_NAME']

In [49]:
data.drop(columns=['FIRST_NAME', 'LAST_NAME'], inplace=True)

In [51]:
data

,Log_ID,emp_id,date,dept,activity,eqpt,EMAIL,full_name
0,1000,115,2022-01-07,Dept6,Cleaning,UPS,AKHOO,Alexander Khoo
1,1001,105,2022-01-08,Dept4,Cleaning,Generator,DAUSTIN,David Austin
2,1002,112,2022-01-09,Dept3,Inspection,CPU,JMURMAN,NaN
3,1003,120,2022-01-10,Dept4,Inspection,UPS,MWEISS,Matthew Weiss
4,1004,138,2022-01-11,Dept3,Checking,Battery,SSTILES,Stephen Stiles
...,...,...,...,...,...,...,...,...
290,1360,122,2023-01-02,Dept2,Repair,AC,PKAUFLING,Payam Kaufling
291,1361,116,2023-01-03,Dept4,Checking,Server,SBAIDA,Shelli Baida
292,1362,110,2023-01-04,Dept4,Checking,CPU,JCHEN,John Chen
293,1363,102,2023-01-05,Dept4,Inspection,AC,LDEHAAN,Lex De Haan
294,1364,128,2023-01-06,Dept3,Cleaning,AC,SMARKLE,Steven Markle

In [53]:
#7
data[data['date'].dt.month == 12] \
    .groupby(['emp_id', 'full_name'])['activity'] \
    .count() \
    .sort_values(ascending=False) \
    .head(1)

emp_id  full_name
102     Lex De Haan    2
Name: activity, dtype: int64

In [59]:
#8

data[data['date'].dt.weekday >= 5] \
  .groupby(['emp_id', 'full_name'])['activity'] \
  .count() \
  .sort_values(ascending=False) \
  .head(3)

emp_id  full_name
109     Daniel Faviet    5
114     Den Raphaely     4
102     Lex De Haan      4
Name: activity, dtype: int64

In [63]:
#9

data[data['date'].dt.weekday < 5] \
  .groupby('activity')['activity'] \
  .count() \
  .sort_values(ascending=False)

activity
Inspection    62
Cleaning      55
Repair        51
Checking      49
Name: activity, dtype: int64

In [64]:
data['days'] = data['date'].dt.day_name()

In [68]:
data.groupby(['days', 'activity'])['activity'].count().swaplevel().unstack()

days        Friday  Monday  Saturday  Sunday  Thursday  Tuesday  Wednesday
activity
Checking         7       9         9      11         8       12         13
Cleaning        15       9         8       9        14        8          9
Inspection      15      11         6      13        14       13          9
Repair           8      12        11      11        11       11          9

### `Q-11`:

1. There are missing value in first name of employee. Fill it using email and last name field.

> E.g- `email` -> JMURMAN and `last_name` -> 'Urman' -> so make it's first name as 'JM', Sort of (Email- lastname).

> Email is constructed from initials of first name concate with lastname. Your Task is to fill first name initials in missing data.

2. You can see email field don't have any domain name. Change this to full email addreess with domain as 'campusx.com'.
E.g- Email field -> `JMURMAN`  result -> `JMURMAN@CAMPUSX.COM`

3. Show Full Name of all the employees whose name starts with 'A' and has done any of these activity ['Incpection', 'Cleaning', 'Checking]

In [73]:
data['full_name'].isna().sum()

np.int64(14)

In [74]:
data.shape

(295, 9)